# Basic Python

## 1. Split this string

In [ ]:
 s = "Hiiii it's me"
 s.split()

['Hiiii', "it's", 'me']

In [ ]:
s = "Hi there Sam!"

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:

output ="The diameter of {planet} is {diameter} kilometers".format(planet="Earth",diameter=12742)
output

'The diameter of Earth is 12742 kilometers'

## 3. In this nest dictionary grab the word "hello"

# Numpy

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]['tricky'][3]['target'][3]

'hello'

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
a1=np.ones(10)*5
a1

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [ ]:

import numpy as St
np=St.arange(20,35,2)
print("Array integers even numbers = ",np)

Array integers even numbers =  [20 22 24 26 28 30 32 34]

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
import numpy as St

np=St.arange(0,9).reshape(3,3)
print("Matrix of 3*3")
print(np)

Matrix of 3*3
[[0 1 2]
 [3 4 5]
 [6 7 8]]

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:

import numpy as St
a=St.array([1,2,3])
b=St.array([4,5,6])
np=St.concatenate((a,b))
print("Total value = ",np)

Total value =  [1 2 3 4 5 6]

## 8. Create a dataframe with 3 rows and 2 columns

# Pandas

In [ ]:
import pandas as pd

In [ ]:
import pandas as St

s1=[['a',1],['b',2],['c',3]]
St.DataFrame(s1,columns=['variables','values'])

  variables  values
0         a       1
1         b       2
2         c       3

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
import pandas as St

St.date_range(start='01-01-2023',end='02-10-2023')

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10'],
              dtype='datetime64[ns]', freq='D')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:

import pandas as St

lists = [[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]
St.DataFrame(lists,columns=['numbers','letters','values'])

   numbers letters  values
0        1     aaa      22
1        2     bbb      25
2        3     ccc      24