# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:
(s.split()) 
['Hi','there','Sam!']

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
('The diameter of earth is {} is{}kilometers.' .format(planet, diameter)) ;

## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
a=np.zeros(10) 
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
a1=np.ones(10)*5
a1

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [ ]:
import numpy as np
array =np.arange(20,36,2)
print("Array of all the even integers from 20 to 35") 
print(array)

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
import numpy as np
array=np.arange(0,9).reshape((3,3))
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
import numpy as np
a=np.array([1,2,3]) 
b=np.array([4,5,6]) 
np.concatenate((a,b),axis=0)

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd

In [ ]:
import pandas as pd
import numpy as np
array1=['s','y']
array2=['a','u']
array3=['m','k']

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
calender = pd.date_range(start='1-1-2023',end ='2-10-2023')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
import pandas as pd
import numpy as np
lists=[[1,'aaa',22],[2 ,'bbb',25],[3,'ccc',24]]
arr=np.array(lists) 
df=pd.DataFrame(arr)
print(df)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24